# Generated by Django 2.2 on 2021-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotobook_app', '0002_auto_20210323_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/none/no-img.jpg', upload_to='images/'),
        ),
    ]
